### ISSUE TITLE
Refactoring Remove empty groups from render

### ISSUE THREAD

**Issue by lindseyindev** [the-collab-lab/tcl-36-smart-shopping-list#32]
Currently if a group is empty the header and background will still be displayed:

![screencapture-localhost-3000-listView-2022-02-19-11_33_19](https://user-images.githubusercontent.com/89806097/154816249-ca0aac4d-4d3f-44ce-9c32-d50c3dd7bef0.png)

To do:

- [ ] Refactor code so that empty groups are hidden.

**Comment by lindseyindev** [comment]
Options to hide group or do a placeholder that the group has no items, indicate that the group is empty but can be filled later, can also make groups accordian style where they can expand

**Comment by rudidev08** [comment]
What do you think about separating this into two issues: essentials (refractor, hiding empty groups) and enhancements (accordion)? That way you can deprioritize enchantments if something else takes precedence and still have basics done, and code-wise, they sound like two separate PRs.
