### ISSUE TITLE
Begin Design Mockup

### ISSUE THREAD

**Issue by shelleymcq** [the-collab-lab/tcl-36-smart-shopping-list#34]
Use Tailwindcss to design the app according to the following wireframe and color scheme.

![image](https://user-images.githubusercontent.com/81432121/155399708-76c1a3b7-78cf-41bf-bbd8-401ebac45c4d.png)

**Comment by rudidev08** [comment]
As you brainstorm/work on this, it's best to document decisions here so it's not lost in Slack. For example, anything else that needs to be done regarding accessibility? Issue to test the design? How should app react to different screen sizes?

**Comment by alenamedved** [comment]
@shelleymcq 
you have to consider that out app will have a submit button also 
and what do you think about making input field for filter and new submit button fixed on the top, so the user have access to it from every part of list (no need to scroll)
