### ISSUE TITLE
Collapse groups functionality

### ISSUE THREAD

**Issue by shelleymcq** [the-collab-lab/tcl-36-smart-shopping-list#42]
Allow the user to collapse and display groups at the touch of a button. For example, they could display only the buy soon items or hide inactive items.

This tutorial might offer some good ideas: https://blog.logrocket.com/create-collapsible-react-components-react-collapsed/

**Comment by lindseyindev** [comment]
<details>
this can be hidden
.
.
.
.
.
.
.
<summary> this is the summary </summary>
.
.
.
.
this line can be hidden too


would need line styling
.
</details>
